name: Docker Build & Push for ECR

on:
  push:
    paths:
      - "30_app/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: "10_資料/30_app"

env:
  WORKING_DIRECTORY: "10_資料/30_app"
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  docker-build-push:
    name: Docker Build & Publish job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        id: build-img
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: tastylog-webapp
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"

      - name: Fetch current task definition
        env:
          TASK_FAMILY: tastylog-test-webapp-template
        run: |
          aws ecs describe-task-definition \
            --task-definition "$TASK_FAMILY" \
            --region "$AWS_REGION" \
            --query 'taskDefinition' > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.WORKING_DIRECTORY }}/task-definition.json
          container-name: webapp
          image: ${{ steps.build-img.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: tastylog-test-webapp-service
          cluster: tastylog-test-webapp-cluster
          wait-for-service-stability: true