name: Hello world !

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"

jobs:
  message:
    name: "Display message"
    runs-on: "ubuntu-20.04"
    steps:
      - run: echo "Hello World"
