name: "[infra] Preview & Deploy"

on:
  push:
    branches:
      - main
    paths:
      - "10_infra/**"
  workflow_dispatch:

env:
  WORKING_DIRECTORY: "10_infra"
  AWS_REGION: ap-northeast-1

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        # if: github.event_name == 'pull_request'
        run: terraform plan -detailed-exitcode -input=false
        continue-on-error: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: 
      - preview
    environment: production
    steps:
      - run: echo "Hello World !"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan
        id: apply
        # if: github.event_name == 'pull_request'
        run: terraform apply -auto-approve -input=false
