name: "[z] workflow1"

on:
  push:
    path:
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  sample:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"

