name: "[z] Hello World"

on:
  push:
    paths:
      - ".github/workflows/**"

jobs:
  sample:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World !"
      - name: Test script
        shell: bash +e {0}
        run: |
          RES=$(exit 2)
          echo $RES
