name: "[z] Hello World"

on:
  push:
    paths:
      - ".github/workflows/**"

jobs:
  sample:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World !"
