name: "[z] Hello World"

on:
  push:
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  sample:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World !"
      - name: Test script
        continue-on-error: true
        shell: bash +e {0}
        run: |
          function main() {
            return 2
          }
          main
          RES=$?
          echo "result: $RES"
