name: "[z] Hello World"

on:
  push:
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  sample:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World !"
      - name: Test script
        shell: bash +e {0}
        run: |
          exit 2
          RES=$?
          echo "result: $RES"
